run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - misspell
    - gosec
    - goconst
    - gocyclo
    - funlen
    - lll
    - whitespace
    - gocritic

linters-settings:
  goimports:
    local-prefixes: github.com/censys/scan-takehome
  gocyclo:
    min-complexity: 15
  funlen:
    lines: 100
    statements: 50
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocyclo
        - lll
    - path: cmd/
      linters:
        - gocyclo
        - funlen
    - path: cmd/scanner
      linters:
        - gosec
        - gocyclo
        - funlen
        - goimports
        - whitespace
    - path: pkg/scanning
      linters:
        - gosec
        - gocyclo
        - funlen